# Generated by Django 4.2.15 on 2024-09-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('request_model', models.CharField(blank=True, max_length=255, null=True)),
                ('request_object', models.CharField(blank=True, max_length=255, null=True)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, default=0, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, default=0, null=True)),
                ('reference_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'openai_request_log',
            },
        ),
    ]
