# Generated by Django 4.2.16 on 2025-05-06 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 6, 17, 0, 44, 93024)),
        ),
        migrations.AlterField(
            model_name='memory',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 6, 17, 0, 44, 92891)),
        ),
        migrations.AlterField(
            model_name='memory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='image_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
