# Generated by Django 4.2.16 on 2025-05-06 17:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0002_alter_journal_content_alter_journal_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='image_link',
        ),
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 6, 17, 14, 25, 807291)),
        ),
        migrations.AlterField(
            model_name='memory',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 6, 17, 14, 25, 807165)),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('of', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.datetime(2025, 5, 6, 17, 14, 25, 807409))),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='echo.memory')),
            ],
            options={
                'db_table': 'echo_gallery',
            },
        ),
    ]
